project:
  type: website
  render:
  - "!x-*.qmd"
  - "!prompts"
  - "!archive"
  - "*.qmd"
  post-render:
    - R/render-recipes.R

website:
  title: "Beer recipes"
  sidebar:
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/critmcdonald/beer-recipes
    contents:
      - href: index.qmd
        text: Recipes
      - href: index-about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    df-print: paged
    code-overflow: wrap